# -*- coding: utf-8 -*-
"""kidney app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Ndtq97DX7h915cTW455H-gKRcPgVPln
"""

import streamlit as st
import pickle
import numpy as np

# Load the trained model
with open('kidney_disease_mlp_model.pkl', 'rb') as file:
    model = pickle.load(file)

# Title of the app
st.title("Kidney Disease Prediction App")
st.subheader("Enter the following parameters:")

# Input fields for each feature
# These are the columns after you transformed numerical into categorical (5 bins)
# So they should be integer entries (0-4)

Sg = st.selectbox('Specific Gravity (Sg)', [0, 1, 2, 3, 4])
Al = st.selectbox('Albumin (Al)', [0, 1, 2, 3, 4])
Su = st.selectbox('Sugar (Su)', [0, 1, 2, 3, 4])
Rbc = st.selectbox('Red Blood Cells (Rbc)', [0, 1])  # Assuming 0-Normal, 1-Abnormal
Htn = st.selectbox('Hypertension (Htn)', [0, 1])     # 0-No, 1-Yes

Bp_c = st.selectbox('Blood Pressure Category (Bp_c)', [0, 1, 2, 3, 4])
Bu_c = st.selectbox('Blood Urea Category (Bu_c)', [0, 1, 2, 3, 4])
Sc_c = st.selectbox('Serum Creatinine Category (Sc_c)', [0, 1, 2, 3, 4])
Sod_c = st.selectbox('Sodium Category (Sod_c)', [0, 1, 2, 3, 4])
Pot_c = st.selectbox('Potassium Category (Pot_c)', [0, 1, 2, 3, 4])
Hemo_c = st.selectbox('Hemoglobin Category (Hemo_c)', [0, 1, 2, 3, 4])
Wbcc_c = st.selectbox('White Blood Cell Count Category (Wbcc_c)', [0, 1, 2, 3, 4])
Rbcc_c = st.selectbox('Red Blood Cell Count Category (Rbcc_c)', [0, 1, 2, 3, 4])

# Predict button
if st.button('Predict'):
    # Prepare the input in the correct order as a 2D array
    input_data = np.array([[Sg, Al, Su, Rbc, Htn, Bp_c, Bu_c, Sc_c, Sod_c, Pot_c, Hemo_c, Wbcc_c, Rbcc_c]])

    # Predict the class
    prediction = model.predict(input_data)

    # Display result
    if prediction[0] == 1:
        st.success("⚠️ Prediction: Likely Kidney Disease Detected!")
    else:
        st.success("✅ Prediction: No Kidney Disease Detected!")

